linkerdVersion: stable-2.7.0
externalIssuer: false
uninstall: false
addOns:
    tracing:
        enabled: true
        collector:
            resources:
                cpu:
                    limit: 100m
                    request: 10m
                memory:
                    limit: 100Mi
                    request: 50Mi:W
        
