linkerdVersion: stable-2.8.1
externalIssuer: false
install:
    skipTest: false
    ha: false
    # upgradeFromVersion: stable-2.7.0
    flags:
        - "--controller-log-level"
        - "debug"
        - "--proxy-log-level"
        - "warn,linkerd2_proxy=debug"
    addOns:
        tracing:
            enabled: true
            collector:
                resources:
                    cpu:
                        limit: 100m
                        request: 10m
                    memory:
                        limit: 100Mi
                        request: 50Mi
    globalControlPlane:
        enable: true
        uninstall: true
inject:
    skipTest: false
    clean: true
