linkerdVersion: stable-2.8.1
externalIssuer: false
controlPlane:
    config:   
        ha: false
        flags:
            - "--controller-log-level"
            - "debug"
            - "--proxy-log-level"
            - "warn,linkerd2_proxy=debug"
        addOns:
            tracing:
                enabled: true
                collector:
                    resources:
                        cpu:
                            limit: 100m
                            request: 10m
                        memory:
                            limit: 100Mi
                            request: 50Mi
lifecycle:
    skip: true
    reinstall: true 
    uninstall: true
inject:
    skip: false
    clean: true
