podSpec:
  containers: []
  restartPolicy: Never
  serviceAccountName: sonobuoy-serviceaccount
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  - key: kubernetes.io/e2e-evict-taint-key
    operator: Exists
      
sonobuoy-config:
  driver: Job
  plugin-name: linkerd2-conformance
  result-format: raw
spec:
  command:
  - /bin/bash
  args:
      - -c 
      - ./conformance -integration-tests -linkerd /root/.linkerd2/bin/linkerd -ginkgo.v -linkerd-namespace l5d-conformance --ginkgo.reportFile=/tmp/results/report.out.xml;
        tar czvf /tmp/results/results.tar.gz -C /tmp/results .;
        echo -n /tmp/results/results.tar.gz > /tmp/results/done
  image: mayankshah1607/linkerd2-conformance
  name: plugin
  resources: {}
  volumeMounts:
  - mountPath: /tmp/results
    name: results
